=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/src/fridgemanagerstorage.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://meinnamespace.meinefirma.de"
			xmlns="http://meinnamespace.meinefirma.de"
			elementFormDefault="qualified">
			
	<!-- Root-Element -->
	<xs:element name="frigdeManagerStorage">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="profiles">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="profile" maxOccurs="unbounded">
			<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"></xs:element>
				<xs:element name="birthdate" type="xs:date"></xs:element>
				<xs:element name="gender" type="xs:string"></xs:element>
				<xs:element name="height" type="xs:float"></xs:element>
				<xs:element name="weight" type="xs:float"></xs:element>
			</xs:sequence>
			</xs:complexType>
			</xs:element>	
		</xs:sequence>
		</xs:complexType>
		</xs:element>	
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/fridgemanagerstorage.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:frigdeManagerStorage xmlns:p="http://meinnamespace.meinefirma.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://meinnamespace.meinefirma.de fridgemanagerstorage.xsd ">
  <p:profiles>
    <p:profile>
      <p:name>Bernd</p:name>
      <p:birthdate>2001-01-01</p:birthdate>
      <p:gender>m</p:gender>
      <p:height>180</p:height>
      <p:weight>70</p:weight>
    </p:profile>
    <p:profile>
      <p:name>Tanja</p:name>
      <p:birthdate>2001-01-01</p:birthdate>
      <p:gender>w</p:gender>
      <p:height>160</p:height>
      <p:weight>60</p:weight>
    </p:profile>
    <p:profile>
      <p:name>Berthold</p:name>
      <p:birthdate>2001-01-01</p:birthdate>
      <p:gender>m</p:gender>
      <p:height>170</p:height>
      <p:weight>90</p:weight>
    </p:profile>
  </p:profiles>
</p:frigdeManagerStorage>
