=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/src/producttypesLOCAL.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://meinnamespace.meinefirma.de"
			xmlns="http://meinnamespace.meinefirma.de"
			elementFormDefault="qualified">
	<!-- Produkttypenliste eines Kühlschranks -->	
<!-- Root-Element -->
<xs:element name="productTypesLOCAL">
<xs:complexType>
<xs:sequence>
	<!-- Produkttyp -->
	<xs:element name="productType" minOccurs="1" maxOccurs="unbounded">
	<xs:complexType>
	<xs:sequence>
		<!-- Name (Schlüssel zu productInformationLOCAL) -->
		<xs:element name="name" type="xs:string"></xs:element>
		<!-- Bestandinformation -->
		<xs:element name="stockData">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="stock" type="xs:int"/>
			<xs:element name="minstock" type="xs:int"/>
		</xs:sequence>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	<xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
	</xs:complexType>
	</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/data/fridges/2/producttypesLOCAL.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:productTypesLOCAL xmlns:p="http://meinnamespace.meinefirma.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://meinnamespace.meinefirma.de producttypesLOCAL.xsd ">
  <p:productType id="1">
    <p:name>delikato Joghurt Dressing Light</p:name>
    <p:stockData>
      <p:stock>1</p:stock>
      <p:minstock>0</p:minstock>
    </p:stockData>
  </p:productType>
  <p:productType id="2">
    <p:name>Milsani Frische Vollmilch</p:name>
    <p:stockData>
      <p:stock>3</p:stock>
      <p:minstock>1</p:minstock>
    </p:stockData>
  </p:productType>
</p:productTypesLOCAL>
