=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/src/newSchemata/notificationsLOCAL.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.teamklinge.de/fridgemanager/schemas" 
	xmlns="http://www.teamklinge.de/fridgemanager/schemas" 
	elementFormDefault="qualified">
			
	<xs:element name="notificationsLOCAL">
	<xs:complexType>
	<xs:sequence>
		<xs:element name="notification" minOccurs="1" maxOccurs="unbounded">
		<xs:complexType>
		<xs:sequence>
			<!-- SchlÃ¼ssel zum Bestitzer/Profil -->
			<xs:element name="profile">
			<xs:complexType>
				<xs:attribute name="id" type="xs:int" use="required"/>
			</xs:complexType>
			</xs:element>
			<!-- Nachrichten-Typ -->
			<xs:element name="type">
				<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="warning"/>
					<xs:enumeration value="notification"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="date" type="xs:date"></xs:element>
			<xs:element name="head" type="xs:string"></xs:element>
			<xs:element name="text" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>	
</xs:schema>

=== JuliaWarkentin/WBA2_Phase2/WBA2_Phase2/data/fridges/2/notificationsLOCAL.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:notificationsLOCAL xmlns:p="http://meinnamespace.meinefirma.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://meinnamespace.meinefirma.de notificationsLOCAL.xsd ">
  <p:notification id="2">
    <p:type>warning</p:type>
    <p:date>2001-01-01</p:date>
    <p:head>A product is nearly expiration!</p:head>
    <p:text>"milsani Frische Vollmilch" l√§uft bald ab.</p:text>
  </p:notification>
  <p:notification id="3">
    <p:type>warning</p:type>
    <p:date>2001-01-01</p:date>
    <p:head>A product was stolen!</p:head>
    <p:text>"milsani Frische Vollmilch" wurde von einer nicht berechtigten Person verbaucht.</p:text>
  </p:notification>
   <p:notification id="4">
    <p:type>notification</p:type>
    <p:date>2001-01-01</p:date>
    <p:head>Products reordered</p:head>
    <p:text>Es wurden 5 "milsani Frische Vollmilch" Produkte nachbestellt.</p:text>
  </p:notification>
</p:notificationsLOCAL>
